inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
  - '{tmp,vendor,yard}/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 80

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Metrics:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
